[build-system]
requires = ["setuptools>=70", "wheel>=0.44"]
build-backend = "setuptools.build_meta"

[project]
name = "envtest"
version = "0.1.0"
description = "Demo package for environments lecture"
requires-python = ">=3.11"
dependencies = [
  "numpy>=2.1",
  "matplotlib>=3.10"
]
